### ISSUE TITLE
Issue with the demo files (probably browser issues)

### ISSUE THREAD

**Issue by meslami2** [tadatitam/info-flow-experiments#16]
Hi,

First thanks for the great work, I really enjoyed both reading the paper and also the code :-)
I couldn't run the demo_exp.py file however. I built a VM using your vagrant file so I have all the requirements you've mentioned. However, I got this error when trying to run the demo file:

WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.

Based on this error, I changed the browser type to "chrome" at this code and also installed google chrome on the VM but then got this error:
WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally

I've read other issues and one sounds to still have an issue with the test files "where the element selenium is attempting to change is not discoverable." However, I'm not sure if this is the same error and I think it's related to the browser. So,  I appreciate if you can help me with this issue.

Thanks :-)

**Comment by ninozong** [comment]
Hi, 
Do you use Ubuntu or Mac os?

**Comment by meslami2** [comment]
My host OS is Windows and I am running the ubuntu VM using the vagrant file in the repository (https://github.com/tadatitam/info-flow-experiments/blob/master/AdFisher/Vagrantfile).

**Comment by ninozong** [comment]
Hi, 
I find this solution work on my computer.
Please change headless=True in the demo_exp.py, which is located in line 14 in the demo_exp.py file. 
Please let me know if it works. Thank you.

**Comment by meslami2** [comment]
thanks, it works properly now :) Thanks for the quick and helpful answer.

**Comment by ninozong** [comment]
No problem :-)

**Comment by meslami2** [comment]
Hi,

I got another issue when make the headless field True that I appreciate if you can help. After a while, I started to get this error:
RuntimeError: Xvfb did not start

with this traceback:
======================================================================
ERROR: runTest (adfisher.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../core/adfisher.py", line 47, in setUp
    self.unit = make_unit(unit_id, treatment_id)
  File "demo_exp.py", line 14, in make_browser
    treatment_id=treatment_id, headless=True, proxy = None)
  File "../core/web/google_news.py", line 32, in __init__
    google_ads.GoogleAdsUnit.__init__(self, browser, log_file, unit_id, treatment_id, headless, proxy=proxy)
  File "../core/web/google_ads.py", line 31, in __init__
    google_search.GoogleSearchUnit.__init__(self, browser, log_file, unit_id, treatment_id, headless, proxy=proxy)
  File "../core/web/google_search.py", line 37, in __init__
    browser_unit.BrowserUnit.__init__(self, browser, log_file, unit_id, treatment_id, headless, proxy=proxy)
  File "../core/web/browser_unit.py", line 17, in __init__
    self.vdisplay.start()
  File "/usr/local/lib/python2.7/dist-packages/xvfbwrapper.py", line 63, in start
    raise RuntimeError('Xvfb did not start')
RuntimeError: Xvfb did not start

I uninstalled Xvfb and installed it again on the vagrant and it started working properly. However, after a while, I started to get the same error again! So, I wanted to know whether you encountered this issue too or you know what can be a solution?

Thanks again for your help.

**Comment by tadatitam** [comment]
By setting headless=True, you are using Xvfb to create a virtual displays for your experiments to run on. This is typically useful when you are using cluster computers (without displays) to run your experiments. 

Xvfb sometimes throws that error when many parallel instances are running together, but it is rare. We were never able to figure out why it occurs since it was not consistent and believe it is due to something internal to xvfb. We get around this problem by collecting data from many many instances, so that these rare failures can be treated as noise.

**Comment by meslami2** [comment]
Thanks for your answer. So, if I set headless=False, I wouldn't get this error (so far I didn't), yes?

**Comment by tadatitam** [comment]
True. With headless=False, Xvfb never comes into play. So, you wouldn't get this error.

**Comment by meslami2** [comment]
Awesome, thanks!
