### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by smcgregor** [tadatitam/info-flow-experiments#2]
Howdy,

I notice there is not a license file or license statement in the repo. Was this intentional? I'm happy to help select one :)

-Sean

**Comment by tadatitam** [comment]
Hi Sean,

This was not intentional, just another item that we have missed out on. We have been looking at the GNU public license, but places extra restrictions on code's reuse to promote open source ideas. What are your thoughts and suggestions?

Amit

**Comment by smcgregor** [comment]
It really depends on what you care about. If you want to force people in the future to share their derived works I would go with GPL. If you want to permit any and all uses of your code I would go with MIT. It comes down to whether you want to use the license as a tool or just want to protect yourself from liability.

**Comment by tadatitam** [comment]
I like the sound of the MIT license, since we want to permit any and all uses of our code. I will discuss this with Michael and Anupam sometime this week, and put that up on the repository.

Thanks!

**Comment by tadatitam** [comment]
Added the GNU GPL v3 license.
