### ISSUE TITLE
Test File Fails

### ISSUE THREAD

**Issue by smcgregor** [tadatitam/info-flow-experiments#5]
It looks like Google may have changed the interface for changing user profiles? I am running the example test script shown in the readme and I get an error where the element selenium is attempting to change is not discoverable. Currently all tests run by the script fail with a similar error.

See: http://pastebin.com/GHKfap1S

**Comment by tadatitam** [comment]
Sorry about that. I updated the scripts. The tests should be working now. Let me know if there are other issues.

Amit

**Comment by smcgregor** [comment]
It is booting up the tests, but they are all failing with this message:

======================================================================
ERROR: test_webdriver (core.experiment.collect.Webdriver)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/smcgregor/Projects/info-flow-experiments/AdFisher/core/experiment/collect.py", line 78, in test_webdriver
    helper.collectMeasurement(driver, MEASUREMENT, ID, TREATMENTID)
  File "/Users/smcgregor/Projects/info-flow-experiments/AdFisher/core/experiment/helper.py", line 71, in collectMeasurement
    age = google.get_age(driver)
  File "/Users/smcgregor/Projects/info-flow-experiments/AdFisher/core/experiment/google_helper.py", line 83, in get_age
    div = driver.find_elements_by_xpath(".//span[@class='"+READ_SPAN+"']")[1]
IndexError: list index out of range

----------------------------------------------------------------------
Ran 1 test in 184.533s

**Comment by tadatitam** [comment]
whoops.
Some parts of this code hasn't been used a while, and so these issues are cropping up. I apologize.
I have fixed them up. it should be working now.
Please don't hesitate in contacting me if something fails again.

Amit

**Comment by smcgregor** [comment]
Thanks Amit, I'll give it a test.

I am thinking of hooking this into TravisCI so you can always know when things break. The only thing I am uncertain of is how to get the dictionary for the NLTK. I believe this has user interaction that would stall installation.

**Comment by smcgregor** [comment]
Also, these experiments take more processor time than is realistic on the free tier of TravisCI. I'll hook it in if there is a (much) shorter version of the testing script.

**Comment by tadatitam** [comment]
Yes, nltk does need user interaction. One option may be to download the corpus into a file, and then add  it to the codebase. 

Most scripts are designed to run for long periods of time. But, it is possible to have a test script doing only some basic steps (like visit 1 website, collect 1 ad, etc.) to be hooked up to TravisCI for testing purposes.

**Comment by smcgregor** [comment]
It is running now :)

How long do they typically last? I have had to quite out because my testbed is currently my laptop. Also, are you changing the user agent string? Advertisers can segment the market based on browser/os combination.

**Comment by tadatitam** [comment]
Great! 

The time taken is completely dependent on the experiment. Some experiments (like the one on gender-jobs discrimination) took about two days, while some others (like the one on dating interests) took half a day.
Currently, AdFisher can run the experiments on either Firefox or Chrome. However, it cannot do so across OSes.

**Comment by smcgregor** [comment]
I assume the length of time is a function of the number of browser instances you can run simultaneously. I am looking into virtualizing the process and contacted SauceLabs about their volume pricing.

**Comment by tadatitam** [comment]
Actually, the length of time is function of the number of blocks in the experiment. In each block, several browser instances run simultaneously. The time taken by a block depends on the treatments applied and the measurements taken. With n blocks, the total time just becomes n times.

**Comment by smcgregor** [comment]
OK, but if you multiplied the number of browser instances available by n, you would be able to complete the experiment in the time it would take to complete a single block?

**Comment by tadatitam** [comment]
Yes, you are right. We have a blocked design because our infrastructure limits the number of browsers we can run at a time. If we can run all the browsers at once, the total time for the experiment would be just as much as it takes to run a single browser.
