### ISSUE TITLE
Google Change/Disable Ads Settings page

### ISSUE THREAD

**Issue by vtoubiana** [tadatitam/info-flow-experiments#8]
Hi,

First congrats for sharing your work.
Sadly it seems that Google's response to your paper has been to remove the ads settings for non-authenticated users: https://www.google.com/settings/ads . So much for transparency, now you can not know on which criteria your are targeted unless you sign-in... Basically no one can reproduce your results now.
I don't think there a lot you can do to solve this "bug", I hope I'm wrong.

Best regards,

Vincent

**Comment by tadatitam** [comment]
You're right, Vincent. Not sure how we can get around this issue. Creating accounts is one way out, but that has its own problems (like captcha and phone numbers), which make it difficult to scale up. Thanks for bringing this to our attention. 

Amit
